apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "media.fullname" . }}
  labels:
    {{- include "media.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.commonEnv | nindent 2 }}
  {{- if .Values.appEnv }}
  {{- toYaml .Values.appEnv | nindent 2 }}
  {{- end }}
