servicePorts:
  - name: client
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: server
    protocol: TCP
    port: 8081
    targetPort: 8081

image:
  repository: lscr.io/linuxserver/calibre
  tag: 6.0.0

ingressEnabled: false
