repositories:
  - name: jetstack
    url: https://charts.jetstack.io

templates:
  default: &default
    namespace: media
    createNamespace: true
    chart: ../charts/media
    values:
      - common/vars.yaml
      - common/encrypted.yaml
      - ./{{`{{ .Release.Name }}`}}/vars.yaml
      - ./{{`{{ .Release.Name }}`}}/encrypted.yaml

releases:
  - name: calibre
    <<: *default
  - name: indexer
    <<: *default
  - name: movies
    <<: *default
  - name: subtitles
    <<: *default
  - name: music
    <<: *default
  - name: tv
    <<: *default
  - name: lazy-librarian
    <<: *default
  - name: cert-manager
    chart: jetstack/cert-manager
    createNamespace: true
    namespace: cert-manager
    version: v1.8.2
    values:
      - ./{{`{{ .Release.Name }}`}}/vars.yaml
  - name: cluster-issuer
    chart: ../charts/cluster-issuer
    values:
      - ./{{`{{ .Release.Name }}`}}/vars.yaml
      - ./{{`{{ .Release.Name }}`}}/encrypted.yaml
  - name: media-ingress
    <<: *default
    chart: ../charts/media-ingress
    values:
      - ./{{`{{ .Release.Name }}`}}/vars.yaml