apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

# .acme.sh/acme.sh --issue --dns dns_cf -d nas02.home.tayarani.net --eab-kid tb_ZSH2Vv4clksCYVfPyQw --eab-hmac-key D8QObfAE7cQtK05MfFxzpdP4r9ZN20cRDL5PPXShXk9b9lKhideulyTG04xMpcirdNlWyjSFBi5CJRv56XOnzA --challenge-alias tayarani.net --force --home .ssl
# .acme.sh/acme.sh --deploy --home .ssl -d nas02.home.tayarani.net --deploy-hook synology_dsm